name: Publish Package

on:
  push:
    tags:
      - 'create-harvide-starter@*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        working-directory: packages/create-harvide-starter
        
      - name: Run tests
        run: bun run test
        working-directory: packages/create-harvide-starter
        
      # - name: Run type check
      #   run: bun typecheck
      #   working-directory: packages/create-harvide-starter

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/create-harvide-starter@')
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        working-directory: packages/create-harvide-starter

      - name: Build create-harvide-starter
        run: bun run build
        working-directory: packages/create-harvide-starter
        
      - name: Publish create-harvide-starter to npm
        run: npm publish --access public
        working-directory: packages/create-harvide-starter
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
